### ISSUE TITLE
Internal Server Shutdown

### ISSUE THREAD

**Issue by benf516** [FossilsArcheologyRevival/FossilArcheology1.7#145]
Hi this is my first time using mods so I'm sure this is a stupid problem and my fault, but what do I do? When I start my world I get a "Internal Server Shutting Down" screen and the game crashes. The crash report I get is as follows, I think.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 100065128 bytes (95 MB) / 255066112 bytes (243 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4156' Renderer: 'Intel(R) HD Graphics 4400'
[22:51:41] [Client thread/INFO] [MinecraftForge]: Attempting early MinecraftForge initialization
[22:51:41] [Client thread/INFO] [FML]: MinecraftForge v10.13.4.1448 Initialized
[22:51:41] [Client thread/INFO] [FML]: Replaced 183 ore recipies
[22:51:41] [Client thread/INFO] [MinecraftForge]: Completed early MinecraftForge initialization
[22:51:41] [Client thread/INFO] [FML]: Found 0 mods from the command line. Injecting into mod discoverer
[22:51:41] [Client thread/INFO] [FML]: Searching C:\Users\Ben\AppData\Roaming\.minecraft\mods for mods
[22:51:46] [Client thread/INFO] [FML]: Forge Mod Loader has identified 4 mods to load
[22:51:46] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, fossil] at CLIENT
[22:51:46] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, fossil] at SERVER
[22:51:48] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Fossils and Archeology Revival
[22:51:48] [Client thread/INFO] [FML]: Processing ObjectHolder annotations
[22:51:48] [Client thread/INFO] [FML]: Found 341 ObjectHolder annotations
[22:51:48] [Client thread/INFO] [FML]: Identifying ItemStackHolder annotations
[22:51:48] [Client thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[22:51:48] [Client thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[22:51:48] [Client thread/INFO] [FML]: Applying holder lookups
[22:51:48] [Client thread/INFO] [FML]: Holder lookups applied
[22:51:48] [Client thread/INFO] [FML]: Injecting itemstacks
[22:51:48] [Client thread/INFO] [FML]: Itemstack injection complete
[22:51:48] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[22:51:48] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[22:51:48] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[22:51:48] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[22:51:49] [Thread-8/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[22:51:49] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[22:51:49] [Sound Library Loader/INFO]: Sound engine started
[22:51:51] [Client thread/INFO]: Created: 512x256 textures/blocks-atlas
[22:51:51] [Client thread/INFO]: Created: 256x256 textures/items-atlas
[22:51:53] [Client thread/INFO] [FML]: Injecting itemstacks
[22:51:53] [Client thread/INFO] [FML]: Itemstack injection complete
[22:51:53] [Client thread/INFO] [FML]: Forge Mod Loader has successfully loaded 4 mods
[22:51:53] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Fossils and Archeology Revival
[22:51:54] [Client thread/INFO]: Created: 512x512 textures/blocks-atlas
[22:51:54] [Client thread/INFO]: Created: 512x512 textures/items-atlas
[22:51:54] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[22:51:54] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: SoundSystem shutting down...
[22:51:54] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:importantMessage:90]:     Author: Paul Lamb, www.paulscode.com
[22:51:54] [Client thread/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[22:51:54] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[22:51:54] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[22:51:54] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[22:51:54] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[22:51:54] [Thread-10/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[22:51:55] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[22:51:55] [Sound Library Loader/INFO]: Sound engine started
[22:52:02] [Client thread/INFO]: Deleting level Dino World
[22:52:02] [Client thread/INFO]: Attempt 1...
[22:52:17] [Server thread/INFO]: Starting integrated minecraft server version 1.7.10
[22:52:17] [Server thread/INFO]: Generating keypair
[22:52:17] [Server thread/INFO]: Converting map!
[22:52:17] [Server thread/INFO]: Scanning folders...
[22:52:17] [Server thread/INFO]: Total conversion count is 0
[22:52:17] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[22:52:17] [Server thread/INFO] [FML]: Applying holder lookups
[22:52:17] [Server thread/INFO] [FML]: Holder lookups applied
[22:52:18] [Server thread/INFO] [FML]: Loading dimension 0 (Dino World) (net.minecraft.server.integrated.IntegratedServer@d4b7d5a)
[22:52:18] [Server thread/INFO] [FML]: Loading dimension 128 (Dino World) (net.minecraft.server.integrated.IntegratedServer@d4b7d5a)
[22:52:18] [Server thread/INFO] [FML]: Loading dimension -34 (Dino World) (net.minecraft.server.integrated.IntegratedServer@d4b7d5a)
[22:52:18] [Server thread/INFO] [FML]: Loading dimension 1 (Dino World) (net.minecraft.server.integrated.IntegratedServer@d4b7d5a)
[22:52:18] [Server thread/INFO] [FML]: Loading dimension -1 (Dino World) (net.minecraft.server.integrated.IntegratedServer@d4b7d5a)
[22:52:18] [Server thread/INFO]: Preparing start region for level 0
[22:52:19] [Server thread/INFO]: Preparing spawn area: 7%
[22:52:20] [Server thread/INFO]: Preparing spawn area: 16%
[22:52:21] [Server thread/INFO]: Preparing spawn area: 28%
[22:52:22] [Server thread/INFO]: Preparing spawn area: 41%
[22:52:23] [Server thread/INFO]: Preparing spawn area: 55%
[22:52:24] [Server thread/INFO]: Preparing spawn area: 72%
[22:52:25] [Server thread/INFO]: Preparing spawn area: 89%
[22:52:25] [Server thread/INFO]: Changing view distance to 32, from 10
[22:52:26] [Netty Client IO #0/INFO] [FML]: Server protocol version 2
[22:52:26] [Netty IO #1/INFO] [FML]: Client protocol version 2
[22:52:26] [Netty IO #1/INFO] [FML]: Client attempting to join with 4 mods : FML@7.10.99.99,Forge@10.13.4.1448,mcp@9.05,fossil@1.7.10 Build 7.2.0
[22:52:26] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [] at CLIENT
[22:52:26] [Netty Client IO #0/INFO] [FML]: Attempting connection with missing mods [] at SERVER
[22:52:26] [Client thread/INFO] [FML]: [Client thread] Client side modded connection established
[22:52:26] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[22:52:26] [Server thread/INFO]: CrazyMadMan516[local:E:700f3614] logged in with entity id 147 at (166.5, 69.0, 260.5)
[22:52:26] [Server thread/INFO]: CrazyMadMan516 joined the game
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory
[22:52:30] [Server thread/OFF] [STRUCTURE GEN API]: Trying to add ItemStack of size 0 to Tile Inventory

-----------------------------------------------------------------------------------------------------------------------
This is the only mod I have installed. I don't know what I'm doing wrong.

**Comment by 4f6f3b** [comment]
Hey, can you post the crash-log? The Forge log doesn't really tell me much.

**Comment by benf516** [comment]
I'd love to, but I don't really know how to do that.

**Comment by 4f6f3b** [comment]
http://i.imgur.com/Uvc7LIy.png You should see a folder called "crash-reports" in your install directory. Just open up the log that you get at the time of the crash.

**Comment by benf516** [comment]
There is no crash reports folder. It may be because it just sticks on the "server shutting down" screen and I have to manually end the Minecraft process myself. If there is nothing else you can do, I understand.

**Comment by 4f6f3b** [comment]
Hmm. Does this happen even if you try starting up a different new world?

**Comment by benf516** [comment]
I hadn't thought to try that. When I opened a pre-existing world with your Mod installed, now I got a crash report.

---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 6/14/15 2:11 PM
Description: Unexpected error

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:70)
	at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
	Level name: MpServer
	All players: 0 total; []
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 0 game time, 0 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 0 total; []
	Retry entities: 0 total; []
	Server brand: ~~ERROR~~ NullPointerException: null
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 68309480 bytes (65 MB) / 273719296 bytes (261 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 4 mods loaded, 4 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	fossil{1.7.10 Build 7.2.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.14.4156' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.14.4156, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

------------------------------------------------------------------------------------------------------
Does this help?

**Comment by 4f6f3b** [comment]
The error report is pretty vague, I'm afraid. You can try using Forge version 1291, just run the .jar and install. 
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.7.10-10.13.2.1291/forge-1.7.10-10.13.2.1291-installer.jar

Otherwise I'll bring it to attention of the other programmers and see if they see what's wrong.

**Comment by benf516** [comment]
Okay, thanks. And thanks for trying.

**Comment by 4f6f3b** [comment]
Hey, if you're still trying to figure out this issue try deleting your .minecraft folder and reinstall Minecraft from scratch. Was just walking through someone else and he managed to get it working and I realized it was the same error! It might have something to do with a corrupt Minecraft options/config file.

**Comment by benf516** [comment]
That worked! Thank you so much!

**Comment by benf516** [comment]
So, once I used 1.8 for the first time since reinstall, The mod no longer works on forge 1.7.10, even if I use regular 1.7.10 first.

**Comment by 4f6f3b** [comment]
So it looks like what's happening is 1.8 changes the options.txt and, most likely the render distance, causes 1.7 to freak out.

What you should be able to do is set up profiles in different folders for 1.7 and 1.8 so they don't share the same files. Like I have my 1.7 F/A installed to C:\Users\Profile\AppData\Roaming\.minecraft\Fossils1710

And 1.8 installed to "C:\Users\Profile\AppData\Roaming\.minecraft\1.8".

**Comment by benf516** [comment]
Okay, I'll try that.

**Comment by benf516** [comment]
That appears to have taken care of everything. Thank you very much again.
