### ISSUE TITLE
Anu Portal crash

### ISSUE THREAD

**Issue by LiteraryRecluse** [FossilsArcheologyRevival/FossilArcheology1.7#170]
Hello, I created the portal in a hellboat but crashed when I tried to enter.  Now my save file is completely inaccessible, as Minecraft crashes whenever I try to open it.  I've created several creative worlds and each one crashed the same way and became "broken" after trying to enter the portal.  Here is the crash report when I try to enter the portal, I'll also post the crash report when I try to open my save after the crash.

Description: Exception generating new chunk

java.lang.ArrayIndexOutOfBoundsException: 32895
	at net.minecraft.world.biome.BiomeGenBase.func_150560_b(BiomeGenBase.java:390)
	at net.minecraft.world.biome.BiomeGenBase.func_150573_a(BiomeGenBase.java:365)
	at mariculture.core.handlers.WorldEventHandler.onReplaceBiomeBlocks(WorldEventHandler.java:66)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_247_WorldEventHandler_onReplaceBiomeBlocks_ReplaceBiomeBlocks.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at mods.fossil.dimension.anu.ChunkProviderAnu.replaceBiomeBlocks(ChunkProviderAnu.java:142)
	at mods.fossil.dimension.anu.ChunkProviderAnu.func_73154_d(ChunkProviderAnu.java:218)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147465_d(World.java:436)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at mods.fossil.handler.AnuTeleporter.func_77185_a(AnuTeleporter.java:70)
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:597)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:504)
	at mods.fossil.blocks.BlockAnuPortal.func_149670_a(BlockAnuPortal.java:55)
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.biome.BiomeGenBase.func_150560_b(BiomeGenBase.java:390)
	at net.minecraft.world.biome.BiomeGenBase.func_150573_a(BiomeGenBase.java:365)
	at mariculture.core.handlers.WorldEventHandler.onReplaceBiomeBlocks(WorldEventHandler.java:66)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_247_WorldEventHandler_onReplaceBiomeBlocks_ReplaceBiomeBlocks.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at mods.fossil.dimension.anu.ChunkProviderAnu.replaceBiomeBlocks(ChunkProviderAnu.java:142)
	at mods.fossil.dimension.anu.ChunkProviderAnu.func_73154_d(ChunkProviderAnu.java:218)

-- Chunk to be generated --
Details:
	Location: -5,-8
	Position hash: -30064771077
	Generator: RandomLevelSource
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:172)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147465_d(World.java:436)
	at net.minecraft.world.World.func_147449_b(World.java:600)
	at mods.fossil.handler.AnuTeleporter.func_77185_a(AnuTeleporter.java:70)
	at net.minecraft.server.management.ServerConfigurationManager.transferEntityToWorld(ServerConfigurationManager.java:597)
	at net.minecraft.server.management.ServerConfigurationManager.transferPlayerToDimension(ServerConfigurationManager.java:504)
	at mods.fossil.blocks.BlockAnuPortal.func_149670_a(BlockAnuPortal.java:55)

-- Block being collided with --
Details:
	Block type: ID #1585 (tile.anu_portal // mods.fossil.blocks.BlockAnuPortal)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (171,35,128), Chunk: (at 11,2,0 in 10,8; contains blocks 160,0,128 to 175,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.entity.Entity.func_145775_I(Entity.java:870)

-- Entity being checked for collision --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 466
	Entity Name: LiteraryRecluse
	Entity's Exact location: -74.00, 63.00, -115.00
	Entity's Block location: World: (-74,63,-115), Chunk: (at 6,3,13 in -5,-8; contains blocks -80,0,-128 to -65,255,-113), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.entity.Entity.func_70091_d(Entity.java:803)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:341)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@46afd157
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by LiteraryRecluse** [comment]
When I try to open the save that crashed:

Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4fd42de3
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by 4f6f3b** [comment]
Can we get the entire uncut crash log? You can post it to pastebin.com and linke the paste for brevity here.

**Comment by LiteraryRecluse** [comment]
Full crash report for the initial crash: http://pastebin.com/tNnRh4qe

**Comment by 4f6f3b** [comment]
"at mariculture.core.handlers.WorldEventHandler.onReplaceBiomeBlocks(WorldEventHandler.java:66)"

You have an issue with the Mariculture mod in your crash report. You're also using 7.2 of Fossils, and I suggest updating to 7.2.1.

**Comment by LiteraryRecluse** [comment]
Yeah, I'm trying to work with the Joshiejack now.  I was told that I needed to add the Ancient Temple dimension to Mariculture's blacklist (it looks like Mariculture is trying to generate ocean-related things in the temple) but I'm not 100 percent sure how to do that.  I'll be sure to update this page if I work it out.

**Comment by 4f6f3b** [comment]
Inside Mariculture's "world-generation.cfg" file, you'll find
```
    I:"Ocean Generation > Blacklisted Dimension IDs" <
        -1
        1
     >
```

The default dimension ids for Fossils is -34 and -23 for Treasure Room and Lair of Darkness. The blacklist should look like

```
    I:"Ocean Generation > Blacklisted Dimension IDs" <
        -1
        1
        -23
        -34
     >
```

**Comment by LiteraryRecluse** [comment]
Ooooh! Okay, I was doing that, but I didn't realize there was a -23 dimension as well. I only saw the Treasure Room id in the config.  I'll try that now, thanks!

**Comment by LiteraryRecluse** [comment]
Adding -23 didn't help, but I was able to make it work was by turning the "replace top block" option off int he Mariculture world config.  It sounds like that can cause problems with ore spawning in Mariculture, but I turned the option back on after I exited the dimension so hopefully things will still be alright.

Anyway, issue resolved!
