### ISSUE TITLE
crash with twilight florest

### ISSUE THREAD

**Issue by jochuan** [FossilsArcheologyRevival/FossilArcheology1.7#187]
the game crashed when i was fighting the lich
---- Minecraft Crash Report ----
// Oops.

Time: 20/07/15 21:48
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at mods.fossil.items.ItemAncientsword.checkHelmet(ItemAncientsword.java:76)
	at mods.fossil.items.ItemAncientsword.func_77644_a(ItemAncientsword.java:41)
	at net.minecraft.item.ItemStack.func_77961_a(Unknown Source)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.fossil.items.ItemAncientsword.checkHelmet(ItemAncientsword.java:76)
	at mods.fossil.items.ItemAncientsword.func_77644_a(ItemAncientsword.java:41)
	at net.minecraft.item.ItemStack.func_77961_a(Unknown Source)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source)
	at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55)
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@1921933
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 177744368 bytes (169 MB) / 727547904 bytes (693 MB) up to 1060372480 bytes (1011 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 3 loaded mod(s)
          - Gammabright version 3.3
          - Uyjulian's X-ray Mod version 9
          - VoxelMap version 1.5.14
	LaunchWrapper: 46 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: optifine.OptiFineClassTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: net.minecraftforge.classloading.FluidIdTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: openeye.asm.MultiTransformer
          - Transformer: api.player.forge.PlayerAPITransformer
          - Transformer: api.player.forge.RenderPlayerAPITransformer
          - Transformer: api.player.forge.RenderPlayerAPIEnhancerTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: me.guichaguri.betterfps.transformers.MathTransformer
          - Transformer: me.guichaguri.betterfps.transformers.EventTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: mods.battlegear2.coremod.transformers.BattlegearAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ModelBipedTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetClientHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.NetServerHandlerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.PlayerControllerMPTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemRendererTransformer
          - Transformer: mods.battlegear2.coremod.transformers.MinecraftTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemStackTransformer
          - Transformer: mods.battlegear2.coremod.transformers.ItemInWorldTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityAIControlledByPlayerTransformer
          - Transformer: mods.battlegear2.coremod.transformers.EntityOtherPlayerMPTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.uyjulian.minecraft.XrayMod.XrayModEventTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 15020, allocated: 1, tallocated: 38
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 Optifine OptiFine_1.7.10_HD_U_C1 19 mods loaded, 19 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	PlayerAPI{1.3} [Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPI{1.3} [Render Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPIEnhancer{1.3} [Render Player API Enhancer] (minecraft.jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar) 
	UCHIJAAAA	zeldaswordskills{1.7.10-2.2.8b} [Zelda Sword Skills] (1.7.10-zeldaswordskills-2.2.8b.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	fossil{1.7.10 Build 7.2.1} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.1.jar) 
	UCHIJAAAA	JASCompatability{1.2.0} [Just Another Spawner Compatibility Addon] (JustAnotherSpawnerCompatibilityAddon-1.2.0.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	zssaddon{1.7.10-alpha-0.0.5-2} [Zelda Sword Skills - Addon] (zeldaswordskillsaddon-v0.0.5a-2-.jar) 
	UCHIJAAAA	JustAnotherSpawner{0.17.1} [Just Another Spawner] (JustAnotherSpawner-0.17.1.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['jochuan'/699, l='warlock', x=770,90, y=101,00, z=322,90]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by Glitchyminecraft** [comment]
it is probably not twilight forest. because it works fine by me and i have exactly the same version. and thaumcraft  is probably the cause, because it crashes when i open minecraft.

**Comment by Glitchyminecraft** [comment]
it is just a case of incompactible mods
